---
title: "Spatial statistics"
author: "Wiegand, Getzin, Hesselbarth"
output: 
  html_document:
    theme: cosmo
---

<br>

Here you can find all practicals for the Spatial statistics course. The practicals will be availaible bit by bit once the topics were covered in the lectures.

You can choose if you prefer using [*Programita*](http://programita.org) or [*R*](https://www.r-project.org) to work on the practicals. Anyways, for the following plenum discussions, I suggest taking screenshots of the results for each exercise.

In case you have any questions or trouble, please write me an e-mail or come to my office at any time. You can find my contact information under "More..." on this homepage.

> To download all data needed for the practicals, [**click here**](Data.zip). Please be aware and credit that the data was published (Getzin et al. 2006, Getzin et al. 2008).

[**Here**](Cheat_sheet.pdf) you can find a cheat sheet for *R* with the most important functions for spatial point pattern analysis. A short introduction can also be found in the ["Getting started with spatstat"](https://cran.r-project.org/web/packages/spatstat/vignettes/getstart.pdf) vignette.

**References**

Getzin, S., Dean, C., He, F., Trofymow, J.A., Wiegand, K., Wiegand, T., 2006. Spatial patterns and competition of tree species in a Douglas fir chronosequence on Vancouver Island. Ecography, 29, 671-682.

Getzin, S., Wiegand, T., Wiegand, K., He, F., 2008. Heterogeneity influences spatial patterns and demographics in forest stands. J. Ecol. 96, 807-820.
